/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "src/counters/counter.v:2" *)
module counter(cnt_max, q, enb, rst_s, ck);
  (* src = "src/counters/counter.v:5" *)
  wire _00_;
  (* src = "src/counters/counter.v:5" *)
  wire _01_;
  (* src = "src/counters/counter.v:5" *)
  wire _02_;
  (* src = "src/counters/counter.v:5" *)
  wire _03_;
  (* src = "src/counters/counter.v:12" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _04_;
  wire [15:0] _05_;
  wire [7:0] _06_;
  wire [3:0] _07_;
  wire [1:0] _08_;
  wire [15:0] _09_;
  wire [7:0] _10_;
  wire [3:0] _11_;
  wire [1:0] _12_;
  wire _13_;
  wire _14_;
  (* src = "src/counters/counter.v:3" *)
  input ck;
  (* src = "src/counters/counter.v:3" *)
  output cnt_max;
  reg cnt_max;
  (* src = "src/counters/counter.v:3" *)
  input enb;
  (* src = "src/counters/counter.v:3" *)
  output q;
  reg q;
  (* src = "src/counters/counter.v:3" *)
  input rst_s;
  assign _05_[1] = _04_[0] |(* src = "src/counters/counter.v:9" *)  q;
  assign _06_[0] = _04_[0] |(* src = "src/counters/counter.v:9" *)  _05_[1];
  assign _07_[0] = _06_[0] |(* src = "src/counters/counter.v:9" *)  q;
  assign _08_[0] = _07_[0] |(* src = "src/counters/counter.v:9" *)  q;
  assign _13_ = _08_[0] |(* src = "src/counters/counter.v:9" *)  q;
  assign _09_[1] = _09_[0] |(* src = "src/counters/counter.v:14" *)  _01_;
  assign _10_[0] = _09_[0] |(* src = "src/counters/counter.v:14" *)  _09_[1];
  assign _11_[0] = _10_[0] |(* src = "src/counters/counter.v:14" *)  _01_;
  assign _12_[0] = _11_[0] |(* src = "src/counters/counter.v:14" *)  _01_;
  assign _14_ = _12_[0] |(* src = "src/counters/counter.v:14" *)  _01_;
  assign _00_ = ~(* src = "src/counters/counter.v:14" *) _14_;
  assign _03_ = _13_ ? (* src = "src/counters/counter.v:9" *) _04_[0] : 1'h0;
  assign _01_ = rst_s ? (* src = "src/counters/counter.v:6" *) 1'h0 : _02_;
  assign _02_ = enb ? (* src = "src/counters/counter.v:8" *) _03_ : q;
  (* src = "src/counters/counter.v:5" *)
  always @(negedge ck)
      cnt_max <= _00_;
  (* src = "src/counters/counter.v:5" *)
  always @(negedge ck)
      q <= _01_;
  assign _09_[0] = _01_ ^(* src = "src/counters/counter.v:14" *)  1'h1;
  assign _04_[0] = q ^(* src = "src/counters/counter.v:12|<techmap.v>:262" *)  1'h1;
  assign _04_[30:1] = { _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31], _04_[31] };
  assign { _05_[15:2], _05_[0] } = { q, q, q, q, q, q, q, q, q, q, q, q, q, q, _04_[0] };
  assign _06_[7:1] = { q, q, q, q, q, q, q };
  assign _07_[3:1] = { q, q, q };
  assign _08_[1] = q;
  assign _09_[15:2] = { _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_ };
  assign _10_[7:1] = { _01_, _01_, _01_, _01_, _01_, _01_, _01_ };
  assign _11_[3:1] = { _01_, _01_, _01_ };
  assign _12_[1] = _01_;
endmodule
