/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "src/maquina_de_estados.v:8" *)
module maquina_de_estados(ck, ch_vm, Vint_z, enb_3, enb_0, rst_s, ch_ref, ch_zr, ld);
  (* src = "src/maquina_de_estados.v:59" *)
  wire _00_;
  (* src = "src/maquina_de_estados.v:59" *)
  wire _01_;
  (* src = "src/maquina_de_estados.v:59" *)
  wire _02_;
  (* src = "src/maquina_de_estados.v:59" *)
  wire _03_;
  (* src = "src/maquina_de_estados.v:35" *)
  wire [2:0] _04_;
  (* src = "src/maquina_de_estados.v:59" *)
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [1:0] _11_;
  wire [1:0] _12_;
  wire [1:0] _13_;
  wire [1:0] _14_;
  wire _15_;
  wire [2:0] _16_;
  wire [2:0] _17_;
  wire [2:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "src/maquina_de_estados.v:70|src/maquina_de_estados.v:61|<techmap.v>:432" *)
  wire [1:0] _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:432" *)
  wire [1:0] _27_;
  (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:432" *)
  wire [11:0] _28_;
  (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:428" *)
  wire [2:0] _29_;
  wire [2:0] _30_;
  wire [2:0] _31_;
  (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *)
  wire _32_;
  (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *)
  wire _33_;
  (* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61|<techmap.v>:445" *)
  wire _34_;
  (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *)
  wire _35_;
  (* src = "src/maquina_de_estados.v:11" *)
  input Vint_z;
  (* src = "src/maquina_de_estados.v:16" *)
  output ch_ref;
  reg ch_ref;
  (* src = "src/maquina_de_estados.v:10" *)
  input ch_vm;
  (* src = "src/maquina_de_estados.v:17" *)
  output ch_zr;
  reg ch_zr;
  (* src = "src/maquina_de_estados.v:9" *)
  input ck;
  (* src = "src/maquina_de_estados.v:13" *)
  output enb_0;
  reg enb_0;
  (* src = "src/maquina_de_estados.v:12" *)
  input enb_3;
  (* init = 3'h0 *)
  (* src = "src/maquina_de_estados.v:22" *)
  reg [2:0] estado = 3'h0;
  (* src = "src/maquina_de_estados.v:18" *)
  output ld;
  reg ld;
  (* init = 3'h0 *)
  (* src = "src/maquina_de_estados.v:22" *)
  reg [2:0] prox_estado = 3'h0;
  (* src = "src/maquina_de_estados.v:14" *)
  output rst_s;
  reg rst_s;
  assign _19_ = _07_ |(* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61" *)  _18_[2];
  assign _08_ = estado[0] |(* src = "src/maquina_de_estados.v:70|src/maquina_de_estados.v:61" *)  _16_[1];
  assign _20_ = _08_ |(* src = "src/maquina_de_estados.v:70|src/maquina_de_estados.v:61" *)  estado[2];
  assign _09_ = _17_[0] |(* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61" *)  estado[1];
  assign _21_ = _09_ |(* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61" *)  estado[2];
  assign _10_ = _17_[0] |(* src = "src/maquina_de_estados.v:76|src/maquina_de_estados.v:61" *)  _16_[1];
  assign _22_ = _10_ |(* src = "src/maquina_de_estados.v:76|src/maquina_de_estados.v:61" *)  estado[2];
  assign _32_ = _25_ |(* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *)  _24_;
  assign _33_ = _06_ |(* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *)  _24_;
  assign _34_ = _26_ |(* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61|<techmap.v>:445" *)  _23_[1];
  assign _29_[2] = _11_[0] |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:441" *)  _11_[1];
  assign _29_[1] = _12_[0] |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:441" *)  _12_[1];
  assign _13_[1] = _28_[6] |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:441" *)  _23_[1];
  assign _29_[0] = _13_[0] |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:441" *)  _13_[1];
  assign _14_[0] = _25_ |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *)  _27_[1];
  assign _14_[1] = _24_ |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *)  _23_[1];
  assign _35_ = _14_[0] |(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *)  _14_[1];
  assign _06_ = _25_ | _23_[1];
  assign _07_ = estado[0] |(* src = "src/maquina_de_estados.v:62|src/maquina_de_estados.v:61" *)  estado[1];
  assign _15_ = _07_ |(* src = "src/maquina_de_estados.v:62|src/maquina_de_estados.v:61" *)  estado[2];
  assign _25_ = ~(* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61" *) _19_;
  assign _24_ = ~(* src = "src/maquina_de_estados.v:70|src/maquina_de_estados.v:61" *) _20_;
  assign _23_[1] = ~(* src = "src/maquina_de_estados.v:62|src/maquina_de_estados.v:61" *) _15_;
  assign _26_ = ~(* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61" *) _21_;
  assign _27_[1] = ~(* src = "src/maquina_de_estados.v:76|src/maquina_de_estados.v:61" *) _22_;
  assign _30_[0] = Vint_z ? (* src = "src/maquina_de_estados.v:50" *) 1'h0 : prox_estado[0];
  assign _30_[1] = Vint_z ? (* src = "src/maquina_de_estados.v:50" *) 1'h0 : prox_estado[1];
  assign _30_[2] = Vint_z ? (* src = "src/maquina_de_estados.v:50" *) 1'h1 : prox_estado[2];
  assign _31_[0] = enb_3 ? (* src = "src/maquina_de_estados.v:46" *) 1'h1 : prox_estado[0];
  assign _31_[1] = enb_3 ? (* src = "src/maquina_de_estados.v:46" *) 1'h1 : prox_estado[1];
  assign _31_[2] = enb_3 ? (* src = "src/maquina_de_estados.v:46" *) 1'h0 : prox_estado[2];
  assign _05_ = _14_[1] ? (* src = "src/maquina_de_estados.v:70|src/maquina_de_estados.v:61|<techmap.v>:445" *) _23_[1] : rst_s;
  assign _02_ = _32_ ? (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *) _24_ : enb_0;
  assign _03_ = _33_ ? (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *) _24_ : ld;
  assign _01_ = _34_ ? (* src = "src/maquina_de_estados.v:67|src/maquina_de_estados.v:61|<techmap.v>:445" *) _23_[1] : ch_zr;
  assign _00_ = _14_[0] ? (* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61|<techmap.v>:445" *) _27_[1] : ch_ref;
  assign _04_[0] = _35_ ? (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *) _29_[0] : prox_estado[0];
  assign _04_[1] = _35_ ? (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *) _29_[1] : prox_estado[1];
  assign _04_[2] = _35_ ? (* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:445" *) _29_[2] : prox_estado[2];
  (* src = "src/maquina_de_estados.v:59" *)
  always @(posedge ck)
      ch_ref <= _00_;
  (* src = "src/maquina_de_estados.v:59" *)
  always @(posedge ck)
      ch_zr <= _01_;
  (* src = "src/maquina_de_estados.v:59" *)
  always @(posedge ck)
      ld <= _03_;
  (* src = "src/maquina_de_estados.v:59" *)
  always @(posedge ck)
      enb_0 <= _02_;
  (* src = "src/maquina_de_estados.v:59" *)
  always @(posedge ck)
      rst_s <= _05_;
  (* src = "src/maquina_de_estados.v:35" *)
  always @(negedge ck)
      prox_estado[0] <= _04_[0];
  (* src = "src/maquina_de_estados.v:35" *)
  always @(negedge ck)
      prox_estado[1] <= _04_[1];
  (* src = "src/maquina_de_estados.v:35" *)
  always @(negedge ck)
      prox_estado[2] <= _04_[2];
  (* src = "src/maquina_de_estados.v:30" *)
  always @(posedge ck)
      estado[0] <= prox_estado[0];
  (* src = "src/maquina_de_estados.v:30" *)
  always @(posedge ck)
      estado[1] <= prox_estado[1];
  (* src = "src/maquina_de_estados.v:30" *)
  always @(posedge ck)
      estado[2] <= prox_estado[2];
  assign _18_[2] = estado[2] ^(* src = "src/maquina_de_estados.v:80|src/maquina_de_estados.v:61" *)  1'h1;
  assign _17_[0] = estado[0] ^(* src = "src/maquina_de_estados.v:76|src/maquina_de_estados.v:61" *)  1'h1;
  assign _16_[1] = estado[1] ^(* src = "src/maquina_de_estados.v:76|src/maquina_de_estados.v:61" *)  1'h1;
  assign _28_[6] = _31_[0] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _24_;
  assign _12_[1] = _31_[1] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _24_;
  assign _11_[1] = _31_[2] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _24_;
  assign _13_[0] = _30_[0] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _27_[1];
  assign _12_[0] = _30_[1] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _27_[1];
  assign _11_[0] = _30_[2] &(* src = "src/maquina_de_estados.v:53|src/maquina_de_estados.v:37|<techmap.v>:434" *)  _27_[1];
  assign _17_[2:1] = estado[2:1];
  assign { _28_[11:7], _28_[5:0] } = { 2'h0, _23_[1], _11_[1], _12_[1], _11_[0], _12_[0], _13_[0], 3'h0 };
  assign _23_[0] = 1'h0;
  assign { _16_[2], _16_[0] } = { estado[2], estado[0] };
  assign _18_[1:0] = estado[1:0];
  assign _27_[0] = 1'h0;
  assign ch_vm = 1'h0;
endmodule
