/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "src/maquina_de_estados.v:1" *)
module maquina_de_estados(ck, inicio, Vint_z, enb_3, enb_0, rst_s, ch_vm, ch_ref, ch_zr, ld);
  (* src = "src/maquina_de_estados.v:49" *)
  wire _000_;
  (* src = "src/maquina_de_estados.v:49" *)
  wire _001_;
  (* src = "src/maquina_de_estados.v:49" *)
  wire _002_;
  (* src = "src/maquina_de_estados.v:49" *)
  wire _003_;
  (* src = "src/maquina_de_estados.v:49" *)
  wire _004_;
  (* src = "src/maquina_de_estados.v:25" *)
  wire [2:0] _005_;
  (* src = "src/maquina_de_estados.v:49" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [1:0] _011_;
  wire _012_;
  wire [1:0] _013_;
  wire _014_;
  wire [1:0] _015_;
  wire _016_;
  wire [1:0] _017_;
  wire _018_;
  wire _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire [2:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  (* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50|<techmap.v>:432" *)
  wire [1:0] _027_;
  wire _028_;
  (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:432" *)
  wire [1:0] _029_;
  wire _030_;
  (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:432" *)
  wire [1:0] _031_;
  (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:432" *)
  wire [14:0] _032_;
  (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:428" *)
  wire [2:0] _033_;
  wire [2:0] _034_;
  wire [2:0] _035_;
  wire [2:0] _036_;
  (* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50|<techmap.v>:445" *)
  wire _037_;
  (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *)
  wire _038_;
  (* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50|<techmap.v>:445" *)
  wire _039_;
  (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *)
  wire _040_;
  (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *)
  wire _041_;
  (* src = "src/maquina_de_estados.v:3" *)
  input Vint_z;
  (* src = "src/maquina_de_estados.v:8" *)
  output ch_ref;
  reg ch_ref;
  (* src = "src/maquina_de_estados.v:7" *)
  output ch_vm;
  reg ch_vm;
  (* src = "src/maquina_de_estados.v:9" *)
  output ch_zr;
  reg ch_zr;
  (* src = "src/maquina_de_estados.v:1" *)
  input ck;
  (* src = "src/maquina_de_estados.v:5" *)
  output enb_0;
  reg enb_0;
  (* src = "src/maquina_de_estados.v:4" *)
  input enb_3;
  (* src = "src/maquina_de_estados.v:2" *)
  input inicio;
  (* src = "src/maquina_de_estados.v:10" *)
  output ld;
  reg ld;
  (* init = 3'h0 *)
  (* src = "src/maquina_de_estados.v:14" *)
  reg [2:0] next_state = 3'h0;
  (* src = "src/maquina_de_estados.v:6" *)
  output rst_s;
  reg rst_s;
  (* init = 3'h0 *)
  (* src = "src/maquina_de_estados.v:14" *)
  reg [2:0] state = 3'h0;
  assign _007_ = _022_[0] |(* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50" *)  state[1];
  assign _023_ = _007_ |(* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50" *)  state[2];
  assign _008_ = state[0] |(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50" *)  state[1];
  assign _024_ = _008_ |(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50" *)  _020_[2];
  assign _009_ = state[0] |(* src = "src/maquina_de_estados.v:60|src/maquina_de_estados.v:50" *)  _021_[1];
  assign _025_ = _009_ |(* src = "src/maquina_de_estados.v:60|src/maquina_de_estados.v:50" *)  state[2];
  assign _010_ = _022_[0] |(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50" *)  _021_[1];
  assign _026_ = _010_ |(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50" *)  state[2];
  assign _041_ = _030_ |(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *)  _027_[1];
  assign _037_ = _028_ |(* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50|<techmap.v>:445" *)  _027_[1];
  assign _038_ = _030_ |(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *)  _029_[1];
  assign _039_ = _031_[1] |(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50|<techmap.v>:445" *)  _029_[1];
  assign _011_[1] = _032_[6] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _032_[9];
  assign _012_ = _011_[0] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _011_[1];
  assign _033_[0] = _012_ |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _027_[1];
  assign _013_[1] = _032_[8] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _032_[11];
  assign _014_ = _013_[0] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _013_[1];
  assign _015_[1] = _032_[7] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _032_[10];
  assign _016_ = _015_[0] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:441" *)  _015_[1];
  assign _017_[0] = _030_ |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *)  _031_[1];
  assign _017_[1] = _029_[1] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *)  _028_;
  assign _018_ = _017_[0] |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *)  _017_[1];
  assign _040_ = _018_ |(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *)  _027_[1];
  assign _019_ = _008_ |(* src = "src/maquina_de_estados.v:51|src/maquina_de_estados.v:50" *)  state[2];
  assign _028_ = ~(* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50" *) _023_;
  assign _027_[1] = ~(* src = "src/maquina_de_estados.v:51|src/maquina_de_estados.v:50" *) _019_;
  assign _030_ = ~(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50" *) _024_;
  assign _029_[1] = ~(* src = "src/maquina_de_estados.v:60|src/maquina_de_estados.v:50" *) _025_;
  assign _031_[1] = ~(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50" *) _026_;
  assign _035_[0] = enb_3 ? (* src = "src/maquina_de_estados.v:36" *) 1'h1 : next_state[0];
  assign _035_[1] = enb_3 ? (* src = "src/maquina_de_estados.v:36" *) 1'h1 : next_state[1];
  assign _035_[2] = enb_3 ? (* src = "src/maquina_de_estados.v:36" *) 1'h0 : next_state[2];
  assign _034_[0] = Vint_z ? (* src = "src/maquina_de_estados.v:40" *) 1'h0 : next_state[0];
  assign _034_[1] = Vint_z ? (* src = "src/maquina_de_estados.v:40" *) 1'h0 : next_state[1];
  assign _034_[2] = Vint_z ? (* src = "src/maquina_de_estados.v:40" *) 1'h1 : next_state[2];
  assign _036_[0] = inicio ? (* src = "src/maquina_de_estados.v:32" *) 1'h0 : next_state[0];
  assign _036_[1] = inicio ? (* src = "src/maquina_de_estados.v:32" *) 1'h1 : next_state[1];
  assign _036_[2] = inicio ? (* src = "src/maquina_de_estados.v:32" *) 1'h0 : next_state[2];
  assign _004_ = _041_ ? (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *) _030_ : ld;
  assign _006_ = _037_ ? (* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50|<techmap.v>:445" *) _027_[1] : rst_s;
  assign _003_ = _038_ ? (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *) _029_[1] : enb_0;
  assign _002_ = _037_ ? (* src = "src/maquina_de_estados.v:56|src/maquina_de_estados.v:50|<techmap.v>:445" *) _027_[1] : ch_zr;
  assign _000_ = _017_[0] ? (* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50|<techmap.v>:445" *) _031_[1] : ch_ref;
  assign _001_ = _039_ ? (* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50|<techmap.v>:445" *) _029_[1] : ch_vm;
  assign _005_[0] = _040_ ? (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *) _033_[0] : next_state[0];
  assign _005_[1] = _040_ ? (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *) _016_ : next_state[1];
  assign _005_[2] = _040_ ? (* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:445" *) _014_ : next_state[2];
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      ch_vm <= _001_;
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      ch_ref <= _000_;
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      ch_zr <= _002_;
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      enb_0 <= _003_;
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      rst_s <= _006_;
  (* src = "src/maquina_de_estados.v:49" *)
  always @(negedge ck)
      ld <= _004_;
  (* src = "src/maquina_de_estados.v:25" *)
  always @(negedge ck)
      next_state[0] <= _005_[0];
  (* src = "src/maquina_de_estados.v:25" *)
  always @(negedge ck)
      next_state[1] <= _005_[1];
  (* src = "src/maquina_de_estados.v:25" *)
  always @(negedge ck)
      next_state[2] <= _005_[2];
  (* src = "src/maquina_de_estados.v:21" *)
  always @(negedge ck)
      state[0] <= next_state[0];
  (* src = "src/maquina_de_estados.v:21" *)
  always @(negedge ck)
      state[1] <= next_state[1];
  (* src = "src/maquina_de_estados.v:21" *)
  always @(negedge ck)
      state[2] <= next_state[2];
  assign _020_[2] = state[2] ^(* src = "src/maquina_de_estados.v:68|src/maquina_de_estados.v:50" *)  1'h1;
  assign _022_[0] = state[0] ^(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50" *)  1'h1;
  assign _021_[1] = state[1] ^(* src = "src/maquina_de_estados.v:64|src/maquina_de_estados.v:50" *)  1'h1;
  assign _032_[9] = _036_[0] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _028_;
  assign _032_[10] = _036_[1] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _028_;
  assign _032_[11] = _036_[2] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _028_;
  assign _032_[6] = _035_[0] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _029_[1];
  assign _032_[7] = _035_[1] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _029_[1];
  assign _032_[8] = _035_[2] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _029_[1];
  assign _011_[0] = _034_[0] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _031_[1];
  assign _015_[0] = _034_[1] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _031_[1];
  assign _013_[0] = _034_[2] &(* src = "src/maquina_de_estados.v:43|src/maquina_de_estados.v:27|<techmap.v>:434" *)  _031_[1];
  assign _029_[0] = 1'h0;
  assign _027_[0] = 1'h0;
  assign _031_[0] = 1'h0;
  assign { _032_[14:12], _032_[5:0] } = { 2'h0, _027_[1], _013_[0], _015_[0], _011_[0], 3'h0 };
  assign _033_[2:1] = { _014_, _016_ };
  assign { _021_[2], _021_[0] } = { state[2], state[0] };
  assign _020_[1:0] = state[1:0];
  assign _022_[2:1] = { state[2], _021_[1] };
endmodule
